// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.1
// source: sessions.proto

package sessions

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Symbols defined in public import of google/protobuf/timestamp.proto.

type Timestamp = timestamp.Timestamp

type PddSessions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int32                `protobuf:"zigzag32,1,opt,name=id,proto3" json:"id,omitempty"`
	TaokeID          int32                `protobuf:"zigzag32,2,opt,name=taokeID,proto3" json:"taokeID,omitempty"`
	ScreenName       string               `protobuf:"bytes,3,opt,name=screenName,proto3" json:"screenName,omitempty"`
	OpenId           string               `protobuf:"bytes,4,opt,name=openId,proto3" json:"openId,omitempty"`
	Token            string               `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	ExpiredAt        *timestamp.Timestamp `protobuf:"bytes,6,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	RefreshToken     string               `protobuf:"bytes,7,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	RefreshExpiredAt *timestamp.Timestamp `protobuf:"bytes,8,opt,name=refreshExpiredAt,proto3" json:"refreshExpiredAt,omitempty"`
	IsDefault        int32                `protobuf:"zigzag32,9,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	CreatedAt        *timestamp.Timestamp `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt        *timestamp.Timestamp `protobuf:"bytes,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *PddSessions) Reset() {
	*x = PddSessions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sessions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PddSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PddSessions) ProtoMessage() {}

func (x *PddSessions) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PddSessions.ProtoReflect.Descriptor instead.
func (*PddSessions) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{0}
}

func (x *PddSessions) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PddSessions) GetTaokeID() int32 {
	if x != nil {
		return x.TaokeID
	}
	return 0
}

func (x *PddSessions) GetScreenName() string {
	if x != nil {
		return x.ScreenName
	}
	return ""
}

func (x *PddSessions) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *PddSessions) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PddSessions) GetExpiredAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *PddSessions) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *PddSessions) GetRefreshExpiredAt() *timestamp.Timestamp {
	if x != nil {
		return x.RefreshExpiredAt
	}
	return nil
}

func (x *PddSessions) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *PddSessions) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PddSessions) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ResponseGetPddSessionsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PddSessions *PddSessions `protobuf:"bytes,1,opt,name=pddSessions,proto3" json:"pddSessions,omitempty"`
}

func (x *ResponseGetPddSessionsInfo) Reset() {
	*x = ResponseGetPddSessionsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sessions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetPddSessionsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetPddSessionsInfo) ProtoMessage() {}

func (x *ResponseGetPddSessionsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetPddSessionsInfo.ProtoReflect.Descriptor instead.
func (*ResponseGetPddSessionsInfo) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseGetPddSessionsInfo) GetPddSessions() *PddSessions {
	if x != nil {
		return x.PddSessions
	}
	return nil
}

type RequestGetPddSessionsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"zigzag32,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RequestGetPddSessionsInfo) Reset() {
	*x = RequestGetPddSessionsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sessions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetPddSessionsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetPddSessionsInfo) ProtoMessage() {}

func (x *RequestGetPddSessionsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetPddSessionsInfo.ProtoReflect.Descriptor instead.
func (*RequestGetPddSessionsInfo) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{2}
}

func (x *RequestGetPddSessionsInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ResponseGetPddSessionsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PddSessions []*PddSessions `protobuf:"bytes,1,rep,name=pddSessions,proto3" json:"pddSessions,omitempty"`
	Total       int32          `protobuf:"zigzag32,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ResponseGetPddSessionsList) Reset() {
	*x = ResponseGetPddSessionsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sessions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetPddSessionsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetPddSessionsList) ProtoMessage() {}

func (x *ResponseGetPddSessionsList) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetPddSessionsList.ProtoReflect.Descriptor instead.
func (*ResponseGetPddSessionsList) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseGetPddSessionsList) GetPddSessions() []*PddSessions {
	if x != nil {
		return x.PddSessions
	}
	return nil
}

func (x *ResponseGetPddSessionsList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RequestGetPddSessionsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page    int32 `protobuf:"zigzag32,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage int32 `protobuf:"zigzag32,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
}

func (x *RequestGetPddSessionsList) Reset() {
	*x = RequestGetPddSessionsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sessions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetPddSessionsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetPddSessionsList) ProtoMessage() {}

func (x *RequestGetPddSessionsList) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetPddSessionsList.ProtoReflect.Descriptor instead.
func (*RequestGetPddSessionsList) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{4}
}

func (x *RequestGetPddSessionsList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RequestGetPddSessionsList) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type RequestAddPddSessions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PddSessions *PddSessions `protobuf:"bytes,1,opt,name=pddSessions,proto3" json:"pddSessions,omitempty"`
}

func (x *RequestAddPddSessions) Reset() {
	*x = RequestAddPddSessions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sessions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAddPddSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAddPddSessions) ProtoMessage() {}

func (x *RequestAddPddSessions) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAddPddSessions.ProtoReflect.Descriptor instead.
func (*RequestAddPddSessions) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{5}
}

func (x *RequestAddPddSessions) GetPddSessions() *PddSessions {
	if x != nil {
		return x.PddSessions
	}
	return nil
}

type ResponseAddPddSessions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PddSessions *PddSessions `protobuf:"bytes,1,opt,name=pddSessions,proto3" json:"pddSessions,omitempty"`
}

func (x *ResponseAddPddSessions) Reset() {
	*x = ResponseAddPddSessions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sessions_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAddPddSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAddPddSessions) ProtoMessage() {}

func (x *ResponseAddPddSessions) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAddPddSessions.ProtoReflect.Descriptor instead.
func (*ResponseAddPddSessions) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseAddPddSessions) GetPddSessions() *PddSessions {
	if x != nil {
		return x.PddSessions
	}
	return nil
}

type RequestUpdatePddSessions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PddSessions *PddSessions `protobuf:"bytes,1,opt,name=pddSessions,proto3" json:"pddSessions,omitempty"`
}

func (x *RequestUpdatePddSessions) Reset() {
	*x = RequestUpdatePddSessions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sessions_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestUpdatePddSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpdatePddSessions) ProtoMessage() {}

func (x *RequestUpdatePddSessions) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpdatePddSessions.ProtoReflect.Descriptor instead.
func (*RequestUpdatePddSessions) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{7}
}

func (x *RequestUpdatePddSessions) GetPddSessions() *PddSessions {
	if x != nil {
		return x.PddSessions
	}
	return nil
}

type ResponseUpdatePddSessions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PddSessions *PddSessions `protobuf:"bytes,1,opt,name=pddSessions,proto3" json:"pddSessions,omitempty"`
}

func (x *ResponseUpdatePddSessions) Reset() {
	*x = ResponseUpdatePddSessions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sessions_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseUpdatePddSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUpdatePddSessions) ProtoMessage() {}

func (x *ResponseUpdatePddSessions) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUpdatePddSessions.ProtoReflect.Descriptor instead.
func (*ResponseUpdatePddSessions) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseUpdatePddSessions) GetPddSessions() *PddSessions {
	if x != nil {
		return x.PddSessions
	}
	return nil
}

type RequestDeletePddSessions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"zigzag32,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RequestDeletePddSessions) Reset() {
	*x = RequestDeletePddSessions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sessions_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDeletePddSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeletePddSessions) ProtoMessage() {}

func (x *RequestDeletePddSessions) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeletePddSessions.ProtoReflect.Descriptor instead.
func (*RequestDeletePddSessions) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{9}
}

func (x *RequestDeletePddSessions) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ResponseDeletePddSessions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResponseDeletePddSessions) Reset() {
	*x = ResponseDeletePddSessions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sessions_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseDeletePddSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDeletePddSessions) ProtoMessage() {}

func (x *ResponseDeletePddSessions) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDeletePddSessions.ProtoReflect.Descriptor instead.
func (*ResponseDeletePddSessions) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{10}
}

var File_sessions_proto protoreflect.FileDescriptor

var file_sessions_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbd, 0x03, 0x0a, 0x0b,
	0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x61, 0x6f, 0x6b, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x07, 0x74, 0x61,
	0x6f, 0x6b, 0x65, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x72, 0x65, 0x65,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x38, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x12, 0x22, 0x0a,
	0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x46, 0x0a, 0x10, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x10, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x11, 0x52, 0x09, 0x69, 0x73,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x38, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x55, 0x0a, 0x1a, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x37, 0x0a, 0x0b, 0x70, 0x64, 0x64,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0b, 0x70, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x2b, 0x0a, 0x19, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74,
	0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x6b, 0x0a, 0x1a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x50, 0x64,
	0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x37, 0x0a,
	0x0b, 0x70, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x64,
	0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0b, 0x70, 0x64, 0x64, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x4a, 0x0a, 0x19,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52,
	0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x22, 0x50, 0x0a, 0x15, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x41, 0x64, 0x64, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x37, 0x0a, 0x0b, 0x70, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0b, 0x70,
	0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x51, 0x0a, 0x16, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x64, 0x64, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x37, 0x0a, 0x0b, 0x70, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x0b, 0x70, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x53, 0x0a,
	0x18, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x64,
	0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x37, 0x0a, 0x0b, 0x70, 0x64, 0x64,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0b, 0x70, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x54, 0x0a, 0x19, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x37, 0x0a, 0x0b, 0x70, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0b, 0x70, 0x64, 0x64,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x2a, 0x0a, 0x18, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x32, 0xe5, 0x03, 0x0a, 0x06, 0x57, 0x61, 0x69, 0x74, 0x65, 0x72, 0x12, 0x55, 0x0a, 0x0e,
	0x41, 0x64, 0x64, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f,
	0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x41, 0x64, 0x64, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x1a,
	0x20, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x41, 0x64, 0x64, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x64, 0x64,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x22, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x23, 0x2e, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x64, 0x64,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x22, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x23, 0x2e, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x2e, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x50,
	0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x24,
	0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x47, 0x65, 0x74, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x64, 0x64,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x23, 0x2e, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47,
	0x65, 0x74, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x50, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_sessions_proto_rawDescOnce sync.Once
	file_sessions_proto_rawDescData = file_sessions_proto_rawDesc
)

func file_sessions_proto_rawDescGZIP() []byte {
	file_sessions_proto_rawDescOnce.Do(func() {
		file_sessions_proto_rawDescData = protoimpl.X.CompressGZIP(file_sessions_proto_rawDescData)
	})
	return file_sessions_proto_rawDescData
}

var file_sessions_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_sessions_proto_goTypes = []interface{}{
	(*PddSessions)(nil),                // 0: sessions.PddSessions
	(*ResponseGetPddSessionsInfo)(nil), // 1: sessions.ResponseGetPddSessionsInfo
	(*RequestGetPddSessionsInfo)(nil),  // 2: sessions.RequestGetPddSessionsInfo
	(*ResponseGetPddSessionsList)(nil), // 3: sessions.ResponseGetPddSessionsList
	(*RequestGetPddSessionsList)(nil),  // 4: sessions.RequestGetPddSessionsList
	(*RequestAddPddSessions)(nil),      // 5: sessions.RequestAddPddSessions
	(*ResponseAddPddSessions)(nil),     // 6: sessions.ResponseAddPddSessions
	(*RequestUpdatePddSessions)(nil),   // 7: sessions.RequestUpdatePddSessions
	(*ResponseUpdatePddSessions)(nil),  // 8: sessions.ResponseUpdatePddSessions
	(*RequestDeletePddSessions)(nil),   // 9: sessions.RequestDeletePddSessions
	(*ResponseDeletePddSessions)(nil),  // 10: sessions.ResponseDeletePddSessions
	(*timestamp.Timestamp)(nil),        // 11: google.protobuf.Timestamp
}
var file_sessions_proto_depIdxs = []int32{
	11, // 0: sessions.PddSessions.expiredAt:type_name -> google.protobuf.Timestamp
	11, // 1: sessions.PddSessions.refreshExpiredAt:type_name -> google.protobuf.Timestamp
	11, // 2: sessions.PddSessions.createdAt:type_name -> google.protobuf.Timestamp
	11, // 3: sessions.PddSessions.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 4: sessions.ResponseGetPddSessionsInfo.pddSessions:type_name -> sessions.PddSessions
	0,  // 5: sessions.ResponseGetPddSessionsList.pddSessions:type_name -> sessions.PddSessions
	0,  // 6: sessions.RequestAddPddSessions.pddSessions:type_name -> sessions.PddSessions
	0,  // 7: sessions.ResponseAddPddSessions.pddSessions:type_name -> sessions.PddSessions
	0,  // 8: sessions.RequestUpdatePddSessions.pddSessions:type_name -> sessions.PddSessions
	0,  // 9: sessions.ResponseUpdatePddSessions.pddSessions:type_name -> sessions.PddSessions
	5,  // 10: sessions.Waiter.AddPddSessions:input_type -> sessions.RequestAddPddSessions
	7,  // 11: sessions.Waiter.UpdatePddSessions:input_type -> sessions.RequestUpdatePddSessions
	9,  // 12: sessions.Waiter.DeletePddSessions:input_type -> sessions.RequestDeletePddSessions
	2,  // 13: sessions.Waiter.GetPddSessionsInfo:input_type -> sessions.RequestGetPddSessionsInfo
	4,  // 14: sessions.Waiter.GetPddSessionsList:input_type -> sessions.RequestGetPddSessionsList
	6,  // 15: sessions.Waiter.AddPddSessions:output_type -> sessions.ResponseAddPddSessions
	8,  // 16: sessions.Waiter.UpdatePddSessions:output_type -> sessions.ResponseUpdatePddSessions
	10, // 17: sessions.Waiter.DeletePddSessions:output_type -> sessions.ResponseDeletePddSessions
	1,  // 18: sessions.Waiter.GetPddSessionsInfo:output_type -> sessions.ResponseGetPddSessionsInfo
	3,  // 19: sessions.Waiter.GetPddSessionsList:output_type -> sessions.ResponseGetPddSessionsList
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_sessions_proto_init() }
func file_sessions_proto_init() {
	if File_sessions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sessions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PddSessions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sessions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetPddSessionsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sessions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetPddSessionsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sessions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetPddSessionsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sessions_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetPddSessionsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sessions_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestAddPddSessions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sessions_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseAddPddSessions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sessions_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestUpdatePddSessions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sessions_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseUpdatePddSessions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sessions_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDeletePddSessions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sessions_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseDeletePddSessions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sessions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sessions_proto_goTypes,
		DependencyIndexes: file_sessions_proto_depIdxs,
		MessageInfos:      file_sessions_proto_msgTypes,
	}.Build()
	File_sessions_proto = out.File
	file_sessions_proto_rawDesc = nil
	file_sessions_proto_goTypes = nil
	file_sessions_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WaiterClient is the client API for Waiter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WaiterClient interface {
	AddPddSessions(ctx context.Context, in *RequestAddPddSessions, opts ...grpc.CallOption) (*ResponseAddPddSessions, error)
	UpdatePddSessions(ctx context.Context, in *RequestUpdatePddSessions, opts ...grpc.CallOption) (*ResponseUpdatePddSessions, error)
	DeletePddSessions(ctx context.Context, in *RequestDeletePddSessions, opts ...grpc.CallOption) (*ResponseDeletePddSessions, error)
	GetPddSessionsInfo(ctx context.Context, in *RequestGetPddSessionsInfo, opts ...grpc.CallOption) (*ResponseGetPddSessionsInfo, error)
	GetPddSessionsList(ctx context.Context, in *RequestGetPddSessionsList, opts ...grpc.CallOption) (*ResponseGetPddSessionsList, error)
}

type waiterClient struct {
	cc grpc.ClientConnInterface
}

func NewWaiterClient(cc grpc.ClientConnInterface) WaiterClient {
	return &waiterClient{cc}
}

func (c *waiterClient) AddPddSessions(ctx context.Context, in *RequestAddPddSessions, opts ...grpc.CallOption) (*ResponseAddPddSessions, error) {
	out := new(ResponseAddPddSessions)
	err := c.cc.Invoke(ctx, "/sessions.Waiter/AddPddSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waiterClient) UpdatePddSessions(ctx context.Context, in *RequestUpdatePddSessions, opts ...grpc.CallOption) (*ResponseUpdatePddSessions, error) {
	out := new(ResponseUpdatePddSessions)
	err := c.cc.Invoke(ctx, "/sessions.Waiter/UpdatePddSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waiterClient) DeletePddSessions(ctx context.Context, in *RequestDeletePddSessions, opts ...grpc.CallOption) (*ResponseDeletePddSessions, error) {
	out := new(ResponseDeletePddSessions)
	err := c.cc.Invoke(ctx, "/sessions.Waiter/DeletePddSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waiterClient) GetPddSessionsInfo(ctx context.Context, in *RequestGetPddSessionsInfo, opts ...grpc.CallOption) (*ResponseGetPddSessionsInfo, error) {
	out := new(ResponseGetPddSessionsInfo)
	err := c.cc.Invoke(ctx, "/sessions.Waiter/GetPddSessionsInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waiterClient) GetPddSessionsList(ctx context.Context, in *RequestGetPddSessionsList, opts ...grpc.CallOption) (*ResponseGetPddSessionsList, error) {
	out := new(ResponseGetPddSessionsList)
	err := c.cc.Invoke(ctx, "/sessions.Waiter/GetPddSessionsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WaiterServer is the server API for Waiter service.
type WaiterServer interface {
	AddPddSessions(context.Context, *RequestAddPddSessions) (*ResponseAddPddSessions, error)
	UpdatePddSessions(context.Context, *RequestUpdatePddSessions) (*ResponseUpdatePddSessions, error)
	DeletePddSessions(context.Context, *RequestDeletePddSessions) (*ResponseDeletePddSessions, error)
	GetPddSessionsInfo(context.Context, *RequestGetPddSessionsInfo) (*ResponseGetPddSessionsInfo, error)
	GetPddSessionsList(context.Context, *RequestGetPddSessionsList) (*ResponseGetPddSessionsList, error)
}

// UnimplementedWaiterServer can be embedded to have forward compatible implementations.
type UnimplementedWaiterServer struct {
}

func (*UnimplementedWaiterServer) AddPddSessions(context.Context, *RequestAddPddSessions) (*ResponseAddPddSessions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPddSessions not implemented")
}
func (*UnimplementedWaiterServer) UpdatePddSessions(context.Context, *RequestUpdatePddSessions) (*ResponseUpdatePddSessions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePddSessions not implemented")
}
func (*UnimplementedWaiterServer) DeletePddSessions(context.Context, *RequestDeletePddSessions) (*ResponseDeletePddSessions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePddSessions not implemented")
}
func (*UnimplementedWaiterServer) GetPddSessionsInfo(context.Context, *RequestGetPddSessionsInfo) (*ResponseGetPddSessionsInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPddSessionsInfo not implemented")
}
func (*UnimplementedWaiterServer) GetPddSessionsList(context.Context, *RequestGetPddSessionsList) (*ResponseGetPddSessionsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPddSessionsList not implemented")
}

func RegisterWaiterServer(s *grpc.Server, srv WaiterServer) {
	s.RegisterService(&_Waiter_serviceDesc, srv)
}

func _Waiter_AddPddSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAddPddSessions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaiterServer).AddPddSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sessions.Waiter/AddPddSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaiterServer).AddPddSessions(ctx, req.(*RequestAddPddSessions))
	}
	return interceptor(ctx, in, info, handler)
}

func _Waiter_UpdatePddSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUpdatePddSessions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaiterServer).UpdatePddSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sessions.Waiter/UpdatePddSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaiterServer).UpdatePddSessions(ctx, req.(*RequestUpdatePddSessions))
	}
	return interceptor(ctx, in, info, handler)
}

func _Waiter_DeletePddSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDeletePddSessions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaiterServer).DeletePddSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sessions.Waiter/DeletePddSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaiterServer).DeletePddSessions(ctx, req.(*RequestDeletePddSessions))
	}
	return interceptor(ctx, in, info, handler)
}

func _Waiter_GetPddSessionsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetPddSessionsInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaiterServer).GetPddSessionsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sessions.Waiter/GetPddSessionsInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaiterServer).GetPddSessionsInfo(ctx, req.(*RequestGetPddSessionsInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Waiter_GetPddSessionsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetPddSessionsList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaiterServer).GetPddSessionsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sessions.Waiter/GetPddSessionsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaiterServer).GetPddSessionsList(ctx, req.(*RequestGetPddSessionsList))
	}
	return interceptor(ctx, in, info, handler)
}

var _Waiter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sessions.Waiter",
	HandlerType: (*WaiterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPddSessions",
			Handler:    _Waiter_AddPddSessions_Handler,
		},
		{
			MethodName: "UpdatePddSessions",
			Handler:    _Waiter_UpdatePddSessions_Handler,
		},
		{
			MethodName: "DeletePddSessions",
			Handler:    _Waiter_DeletePddSessions_Handler,
		},
		{
			MethodName: "GetPddSessionsInfo",
			Handler:    _Waiter_GetPddSessionsInfo_Handler,
		},
		{
			MethodName: "GetPddSessionsList",
			Handler:    _Waiter_GetPddSessionsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sessions.proto",
}
